### ISSUE TITLE
MacOS build error in CI

### ISSUE THREAD

**Issue by ajlennon** [samsface/godot-native-example#11]
Hi there,

Just trying to have a little play with this. I forked and kicked off the CI and the Mac workflow errors:

https://github.com/DynamicDevices/godot-native-example/actions/runs/9021867142/job/24790093786

Any ideas?

Thanks!

Alex

**Comment by samsface** [comment]
If you check in my othe git repos, I fixed this ci issue in godot-steam-api. 

Though probably you want to not use this repo? It’s for Godot 3.x. Godot 4 uses a new systems to talk with c++

**Comment by ajlennon** [comment]
Thanks!
