### ISSUE TITLE
how to set up for Linux/Ubuntu?

### ISSUE THREAD

**Issue by ShadowFungi** [samsface/godot-native-example#2]
Hope you're <insert time of day here> is going well.
But I would like some help finding all the prerequisites, and setting this up in Ubuntu, I already know a few of them such as Mono, git, and Python3 along with their dependencies and an IDE which I have been on the hunt for. However since this isn't Windows there are going to be at least a few differences with setup, so I would like help finding what those differences are, and what to do to get around those.

**Comment by samsface** [comment]
This installs the tools you'll need

```sh
sudo apt-get update && apt-get install build-essential cmake python3-pip
pip3 install conan==1.40.3
```

Run this script to build the project in debug mode:
```sh
./debug.sh
```
